// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VeloPass.Infrastructure.Data.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_User_Email : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "email",
                schema: "public",
                table: "users",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "name",
                schema: "public",
                table: "users",
                type: "text",
                nullable: false,
                defaultValue: "");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "email",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "name",
                schema: "public",
                table: "users");
        }
    }
}
